//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name nume from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertAgentii", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.InsertAgentiiResponse InsertAgentii(WindowsFormsApp1.ServiceReference1.InsertAgentiiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertAgentii", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.InsertAgentiiResponse> InsertAgentiiAsync(WindowsFormsApp1.ServiceReference1.InsertAgentiiRequest request);
        
        // CODEGEN: Generating message contract since element name nume from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAgentii", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.UpdateAgentiiResponse UpdateAgentii(WindowsFormsApp1.ServiceReference1.UpdateAgentiiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAgentii", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.UpdateAgentiiResponse> UpdateAgentiiAsync(WindowsFormsApp1.ServiceReference1.UpdateAgentiiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteAgentii", ReplyAction="*")]
        void DeleteAgentii(int id_agentie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteAgentii", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteAgentiiAsync(int id_agentie);
        
        // CODEGEN: Generating message contract since element name vanzare from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateOferta", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.UpdateOfertaResponse UpdateOferta(WindowsFormsApp1.ServiceReference1.UpdateOfertaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateOferta", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.UpdateOfertaResponse> UpdateOfertaAsync(WindowsFormsApp1.ServiceReference1.UpdateOfertaRequest request);
        
        // CODEGEN: Generating message contract since element name vanzare from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertOferta", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.InsertOfertaResponse InsertOferta(WindowsFormsApp1.ServiceReference1.InsertOfertaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertOferta", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.InsertOfertaResponse> InsertOfertaAsync(WindowsFormsApp1.ServiceReference1.InsertOfertaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteOferta", ReplyAction="*")]
        void DeleteOferta(int id_spatiu, int id_agentie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteOferta", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteOfertaAsync(int id_spatiu, int id_agentie);
        
        // CODEGEN: Generating message contract since element name adresa from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertSpatiu", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.InsertSpatiuResponse InsertSpatiu(WindowsFormsApp1.ServiceReference1.InsertSpatiuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertSpatiu", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.InsertSpatiuResponse> InsertSpatiuAsync(WindowsFormsApp1.ServiceReference1.InsertSpatiuRequest request);
        
        // CODEGEN: Generating message contract since element name adresa from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSpatiu", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.UpdateSpatiuResponse UpdateSpatiu(WindowsFormsApp1.ServiceReference1.UpdateSpatiuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSpatiu", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.UpdateSpatiuResponse> UpdateSpatiuAsync(WindowsFormsApp1.ServiceReference1.UpdateSpatiuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSpatiu", ReplyAction="*")]
        void DeleteSpatiu(int id_spatiu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSpatiu", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteSpatiuAsync(int id_spatiu);
        
        // CODEGEN: Generating message contract since element name denumire from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTip", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.UpdateTipResponse UpdateTip(WindowsFormsApp1.ServiceReference1.UpdateTipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTip", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.UpdateTipResponse> UpdateTipAsync(WindowsFormsApp1.ServiceReference1.UpdateTipRequest request);
        
        // CODEGEN: Generating message contract since element name denumire from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertTip", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.InsertTipResponse InsertTip(WindowsFormsApp1.ServiceReference1.InsertTipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertTip", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.InsertTipResponse> InsertTipAsync(WindowsFormsApp1.ServiceReference1.InsertTipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteTip", ReplyAction="*")]
        void DeleteTip(int id_tip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteTip", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteTipAsync(int id_tip);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertAgentiiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertAgentii", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.InsertAgentiiRequestBody Body;
        
        public InsertAgentiiRequest() {
        }
        
        public InsertAgentiiRequest(WindowsFormsApp1.ServiceReference1.InsertAgentiiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertAgentiiRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nume;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        public InsertAgentiiRequestBody() {
        }
        
        public InsertAgentiiRequestBody(string nume, string email) {
            this.nume = nume;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertAgentiiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertAgentiiResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.InsertAgentiiResponseBody Body;
        
        public InsertAgentiiResponse() {
        }
        
        public InsertAgentiiResponse(WindowsFormsApp1.ServiceReference1.InsertAgentiiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertAgentiiResponseBody {
        
        public InsertAgentiiResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateAgentiiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAgentii", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.UpdateAgentiiRequestBody Body;
        
        public UpdateAgentiiRequest() {
        }
        
        public UpdateAgentiiRequest(WindowsFormsApp1.ServiceReference1.UpdateAgentiiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateAgentiiRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nume;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        public UpdateAgentiiRequestBody() {
        }
        
        public UpdateAgentiiRequestBody(int id, string nume, string email) {
            this.id = id;
            this.nume = nume;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateAgentiiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAgentiiResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.UpdateAgentiiResponseBody Body;
        
        public UpdateAgentiiResponse() {
        }
        
        public UpdateAgentiiResponse(WindowsFormsApp1.ServiceReference1.UpdateAgentiiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateAgentiiResponseBody {
        
        public UpdateAgentiiResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateOfertaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateOferta", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.UpdateOfertaRequestBody Body;
        
        public UpdateOfertaRequest() {
        }
        
        public UpdateOfertaRequest(WindowsFormsApp1.ServiceReference1.UpdateOfertaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateOfertaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_agentie;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int id_spatiu;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string vanzare;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int pret;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string moneda;
        
        public UpdateOfertaRequestBody() {
        }
        
        public UpdateOfertaRequestBody(int id_agentie, int id_spatiu, string vanzare, int pret, string moneda) {
            this.id_agentie = id_agentie;
            this.id_spatiu = id_spatiu;
            this.vanzare = vanzare;
            this.pret = pret;
            this.moneda = moneda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateOfertaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateOfertaResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.UpdateOfertaResponseBody Body;
        
        public UpdateOfertaResponse() {
        }
        
        public UpdateOfertaResponse(WindowsFormsApp1.ServiceReference1.UpdateOfertaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateOfertaResponseBody {
        
        public UpdateOfertaResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertOfertaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertOferta", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.InsertOfertaRequestBody Body;
        
        public InsertOfertaRequest() {
        }
        
        public InsertOfertaRequest(WindowsFormsApp1.ServiceReference1.InsertOfertaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertOfertaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_agentie;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int id_spatiu;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string vanzare;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int pret;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string moneda;
        
        public InsertOfertaRequestBody() {
        }
        
        public InsertOfertaRequestBody(int id_agentie, int id_spatiu, string vanzare, int pret, string moneda) {
            this.id_agentie = id_agentie;
            this.id_spatiu = id_spatiu;
            this.vanzare = vanzare;
            this.pret = pret;
            this.moneda = moneda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertOfertaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertOfertaResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.InsertOfertaResponseBody Body;
        
        public InsertOfertaResponse() {
        }
        
        public InsertOfertaResponse(WindowsFormsApp1.ServiceReference1.InsertOfertaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertOfertaResponseBody {
        
        public InsertOfertaResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertSpatiuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertSpatiu", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.InsertSpatiuRequestBody Body;
        
        public InsertSpatiuRequest() {
        }
        
        public InsertSpatiuRequest(WindowsFormsApp1.ServiceReference1.InsertSpatiuRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertSpatiuRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string adresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int zona;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int suprafata;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int id_tip;
        
        public InsertSpatiuRequestBody() {
        }
        
        public InsertSpatiuRequestBody(string adresa, int zona, int suprafata, int id_tip) {
            this.adresa = adresa;
            this.zona = zona;
            this.suprafata = suprafata;
            this.id_tip = id_tip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertSpatiuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertSpatiuResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.InsertSpatiuResponseBody Body;
        
        public InsertSpatiuResponse() {
        }
        
        public InsertSpatiuResponse(WindowsFormsApp1.ServiceReference1.InsertSpatiuResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertSpatiuResponseBody {
        
        public InsertSpatiuResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSpatiuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSpatiu", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.UpdateSpatiuRequestBody Body;
        
        public UpdateSpatiuRequest() {
        }
        
        public UpdateSpatiuRequest(WindowsFormsApp1.ServiceReference1.UpdateSpatiuRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSpatiuRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_spatiu;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string adresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int zona;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int suprafata;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int id_tip;
        
        public UpdateSpatiuRequestBody() {
        }
        
        public UpdateSpatiuRequestBody(int id_spatiu, string adresa, int zona, int suprafata, int id_tip) {
            this.id_spatiu = id_spatiu;
            this.adresa = adresa;
            this.zona = zona;
            this.suprafata = suprafata;
            this.id_tip = id_tip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSpatiuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSpatiuResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.UpdateSpatiuResponseBody Body;
        
        public UpdateSpatiuResponse() {
        }
        
        public UpdateSpatiuResponse(WindowsFormsApp1.ServiceReference1.UpdateSpatiuResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateSpatiuResponseBody {
        
        public UpdateSpatiuResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTip", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.UpdateTipRequestBody Body;
        
        public UpdateTipRequest() {
        }
        
        public UpdateTipRequest(WindowsFormsApp1.ServiceReference1.UpdateTipRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateTipRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_tip;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string denumire;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string caracteristici;
        
        public UpdateTipRequestBody() {
        }
        
        public UpdateTipRequestBody(int id_tip, string denumire, string caracteristici) {
            this.id_tip = id_tip;
            this.denumire = denumire;
            this.caracteristici = caracteristici;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTipResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.UpdateTipResponseBody Body;
        
        public UpdateTipResponse() {
        }
        
        public UpdateTipResponse(WindowsFormsApp1.ServiceReference1.UpdateTipResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateTipResponseBody {
        
        public UpdateTipResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertTipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertTip", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.InsertTipRequestBody Body;
        
        public InsertTipRequest() {
        }
        
        public InsertTipRequest(WindowsFormsApp1.ServiceReference1.InsertTipRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertTipRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string denumire;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string caracteristici;
        
        public InsertTipRequestBody() {
        }
        
        public InsertTipRequestBody(string denumire, string caracteristici) {
            this.denumire = denumire;
            this.caracteristici = caracteristici;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertTipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertTipResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.InsertTipResponseBody Body;
        
        public InsertTipResponse() {
        }
        
        public InsertTipResponse(WindowsFormsApp1.ServiceReference1.InsertTipResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertTipResponseBody {
        
        public InsertTipResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WindowsFormsApp1.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.WebService1Soap>, WindowsFormsApp1.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.InsertAgentiiResponse WindowsFormsApp1.ServiceReference1.WebService1Soap.InsertAgentii(WindowsFormsApp1.ServiceReference1.InsertAgentiiRequest request) {
            return base.Channel.InsertAgentii(request);
        }
        
        public void InsertAgentii(string nume, string email) {
            WindowsFormsApp1.ServiceReference1.InsertAgentiiRequest inValue = new WindowsFormsApp1.ServiceReference1.InsertAgentiiRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.InsertAgentiiRequestBody();
            inValue.Body.nume = nume;
            inValue.Body.email = email;
            WindowsFormsApp1.ServiceReference1.InsertAgentiiResponse retVal = ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).InsertAgentii(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.InsertAgentiiResponse> WindowsFormsApp1.ServiceReference1.WebService1Soap.InsertAgentiiAsync(WindowsFormsApp1.ServiceReference1.InsertAgentiiRequest request) {
            return base.Channel.InsertAgentiiAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.InsertAgentiiResponse> InsertAgentiiAsync(string nume, string email) {
            WindowsFormsApp1.ServiceReference1.InsertAgentiiRequest inValue = new WindowsFormsApp1.ServiceReference1.InsertAgentiiRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.InsertAgentiiRequestBody();
            inValue.Body.nume = nume;
            inValue.Body.email = email;
            return ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).InsertAgentiiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.UpdateAgentiiResponse WindowsFormsApp1.ServiceReference1.WebService1Soap.UpdateAgentii(WindowsFormsApp1.ServiceReference1.UpdateAgentiiRequest request) {
            return base.Channel.UpdateAgentii(request);
        }
        
        public void UpdateAgentii(int id, string nume, string email) {
            WindowsFormsApp1.ServiceReference1.UpdateAgentiiRequest inValue = new WindowsFormsApp1.ServiceReference1.UpdateAgentiiRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.UpdateAgentiiRequestBody();
            inValue.Body.id = id;
            inValue.Body.nume = nume;
            inValue.Body.email = email;
            WindowsFormsApp1.ServiceReference1.UpdateAgentiiResponse retVal = ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).UpdateAgentii(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.UpdateAgentiiResponse> WindowsFormsApp1.ServiceReference1.WebService1Soap.UpdateAgentiiAsync(WindowsFormsApp1.ServiceReference1.UpdateAgentiiRequest request) {
            return base.Channel.UpdateAgentiiAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.UpdateAgentiiResponse> UpdateAgentiiAsync(int id, string nume, string email) {
            WindowsFormsApp1.ServiceReference1.UpdateAgentiiRequest inValue = new WindowsFormsApp1.ServiceReference1.UpdateAgentiiRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.UpdateAgentiiRequestBody();
            inValue.Body.id = id;
            inValue.Body.nume = nume;
            inValue.Body.email = email;
            return ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).UpdateAgentiiAsync(inValue);
        }
        
        public void DeleteAgentii(int id_agentie) {
            base.Channel.DeleteAgentii(id_agentie);
        }
        
        public System.Threading.Tasks.Task DeleteAgentiiAsync(int id_agentie) {
            return base.Channel.DeleteAgentiiAsync(id_agentie);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.UpdateOfertaResponse WindowsFormsApp1.ServiceReference1.WebService1Soap.UpdateOferta(WindowsFormsApp1.ServiceReference1.UpdateOfertaRequest request) {
            return base.Channel.UpdateOferta(request);
        }
        
        public void UpdateOferta(int id_agentie, int id_spatiu, string vanzare, int pret, string moneda) {
            WindowsFormsApp1.ServiceReference1.UpdateOfertaRequest inValue = new WindowsFormsApp1.ServiceReference1.UpdateOfertaRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.UpdateOfertaRequestBody();
            inValue.Body.id_agentie = id_agentie;
            inValue.Body.id_spatiu = id_spatiu;
            inValue.Body.vanzare = vanzare;
            inValue.Body.pret = pret;
            inValue.Body.moneda = moneda;
            WindowsFormsApp1.ServiceReference1.UpdateOfertaResponse retVal = ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).UpdateOferta(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.UpdateOfertaResponse> WindowsFormsApp1.ServiceReference1.WebService1Soap.UpdateOfertaAsync(WindowsFormsApp1.ServiceReference1.UpdateOfertaRequest request) {
            return base.Channel.UpdateOfertaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.UpdateOfertaResponse> UpdateOfertaAsync(int id_agentie, int id_spatiu, string vanzare, int pret, string moneda) {
            WindowsFormsApp1.ServiceReference1.UpdateOfertaRequest inValue = new WindowsFormsApp1.ServiceReference1.UpdateOfertaRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.UpdateOfertaRequestBody();
            inValue.Body.id_agentie = id_agentie;
            inValue.Body.id_spatiu = id_spatiu;
            inValue.Body.vanzare = vanzare;
            inValue.Body.pret = pret;
            inValue.Body.moneda = moneda;
            return ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).UpdateOfertaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.InsertOfertaResponse WindowsFormsApp1.ServiceReference1.WebService1Soap.InsertOferta(WindowsFormsApp1.ServiceReference1.InsertOfertaRequest request) {
            return base.Channel.InsertOferta(request);
        }
        
        public void InsertOferta(int id_agentie, int id_spatiu, string vanzare, int pret, string moneda) {
            WindowsFormsApp1.ServiceReference1.InsertOfertaRequest inValue = new WindowsFormsApp1.ServiceReference1.InsertOfertaRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.InsertOfertaRequestBody();
            inValue.Body.id_agentie = id_agentie;
            inValue.Body.id_spatiu = id_spatiu;
            inValue.Body.vanzare = vanzare;
            inValue.Body.pret = pret;
            inValue.Body.moneda = moneda;
            WindowsFormsApp1.ServiceReference1.InsertOfertaResponse retVal = ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).InsertOferta(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.InsertOfertaResponse> WindowsFormsApp1.ServiceReference1.WebService1Soap.InsertOfertaAsync(WindowsFormsApp1.ServiceReference1.InsertOfertaRequest request) {
            return base.Channel.InsertOfertaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.InsertOfertaResponse> InsertOfertaAsync(int id_agentie, int id_spatiu, string vanzare, int pret, string moneda) {
            WindowsFormsApp1.ServiceReference1.InsertOfertaRequest inValue = new WindowsFormsApp1.ServiceReference1.InsertOfertaRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.InsertOfertaRequestBody();
            inValue.Body.id_agentie = id_agentie;
            inValue.Body.id_spatiu = id_spatiu;
            inValue.Body.vanzare = vanzare;
            inValue.Body.pret = pret;
            inValue.Body.moneda = moneda;
            return ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).InsertOfertaAsync(inValue);
        }
        
        public void DeleteOferta(int id_spatiu, int id_agentie) {
            base.Channel.DeleteOferta(id_spatiu, id_agentie);
        }
        
        public System.Threading.Tasks.Task DeleteOfertaAsync(int id_spatiu, int id_agentie) {
            return base.Channel.DeleteOfertaAsync(id_spatiu, id_agentie);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.InsertSpatiuResponse WindowsFormsApp1.ServiceReference1.WebService1Soap.InsertSpatiu(WindowsFormsApp1.ServiceReference1.InsertSpatiuRequest request) {
            return base.Channel.InsertSpatiu(request);
        }
        
        public void InsertSpatiu(string adresa, int zona, int suprafata, int id_tip) {
            WindowsFormsApp1.ServiceReference1.InsertSpatiuRequest inValue = new WindowsFormsApp1.ServiceReference1.InsertSpatiuRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.InsertSpatiuRequestBody();
            inValue.Body.adresa = adresa;
            inValue.Body.zona = zona;
            inValue.Body.suprafata = suprafata;
            inValue.Body.id_tip = id_tip;
            WindowsFormsApp1.ServiceReference1.InsertSpatiuResponse retVal = ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).InsertSpatiu(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.InsertSpatiuResponse> WindowsFormsApp1.ServiceReference1.WebService1Soap.InsertSpatiuAsync(WindowsFormsApp1.ServiceReference1.InsertSpatiuRequest request) {
            return base.Channel.InsertSpatiuAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.InsertSpatiuResponse> InsertSpatiuAsync(string adresa, int zona, int suprafata, int id_tip) {
            WindowsFormsApp1.ServiceReference1.InsertSpatiuRequest inValue = new WindowsFormsApp1.ServiceReference1.InsertSpatiuRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.InsertSpatiuRequestBody();
            inValue.Body.adresa = adresa;
            inValue.Body.zona = zona;
            inValue.Body.suprafata = suprafata;
            inValue.Body.id_tip = id_tip;
            return ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).InsertSpatiuAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.UpdateSpatiuResponse WindowsFormsApp1.ServiceReference1.WebService1Soap.UpdateSpatiu(WindowsFormsApp1.ServiceReference1.UpdateSpatiuRequest request) {
            return base.Channel.UpdateSpatiu(request);
        }
        
        public void UpdateSpatiu(int id_spatiu, string adresa, int zona, int suprafata, int id_tip) {
            WindowsFormsApp1.ServiceReference1.UpdateSpatiuRequest inValue = new WindowsFormsApp1.ServiceReference1.UpdateSpatiuRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.UpdateSpatiuRequestBody();
            inValue.Body.id_spatiu = id_spatiu;
            inValue.Body.adresa = adresa;
            inValue.Body.zona = zona;
            inValue.Body.suprafata = suprafata;
            inValue.Body.id_tip = id_tip;
            WindowsFormsApp1.ServiceReference1.UpdateSpatiuResponse retVal = ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).UpdateSpatiu(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.UpdateSpatiuResponse> WindowsFormsApp1.ServiceReference1.WebService1Soap.UpdateSpatiuAsync(WindowsFormsApp1.ServiceReference1.UpdateSpatiuRequest request) {
            return base.Channel.UpdateSpatiuAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.UpdateSpatiuResponse> UpdateSpatiuAsync(int id_spatiu, string adresa, int zona, int suprafata, int id_tip) {
            WindowsFormsApp1.ServiceReference1.UpdateSpatiuRequest inValue = new WindowsFormsApp1.ServiceReference1.UpdateSpatiuRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.UpdateSpatiuRequestBody();
            inValue.Body.id_spatiu = id_spatiu;
            inValue.Body.adresa = adresa;
            inValue.Body.zona = zona;
            inValue.Body.suprafata = suprafata;
            inValue.Body.id_tip = id_tip;
            return ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).UpdateSpatiuAsync(inValue);
        }
        
        public void DeleteSpatiu(int id_spatiu) {
            base.Channel.DeleteSpatiu(id_spatiu);
        }
        
        public System.Threading.Tasks.Task DeleteSpatiuAsync(int id_spatiu) {
            return base.Channel.DeleteSpatiuAsync(id_spatiu);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.UpdateTipResponse WindowsFormsApp1.ServiceReference1.WebService1Soap.UpdateTip(WindowsFormsApp1.ServiceReference1.UpdateTipRequest request) {
            return base.Channel.UpdateTip(request);
        }
        
        public void UpdateTip(int id_tip, string denumire, string caracteristici) {
            WindowsFormsApp1.ServiceReference1.UpdateTipRequest inValue = new WindowsFormsApp1.ServiceReference1.UpdateTipRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.UpdateTipRequestBody();
            inValue.Body.id_tip = id_tip;
            inValue.Body.denumire = denumire;
            inValue.Body.caracteristici = caracteristici;
            WindowsFormsApp1.ServiceReference1.UpdateTipResponse retVal = ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).UpdateTip(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.UpdateTipResponse> WindowsFormsApp1.ServiceReference1.WebService1Soap.UpdateTipAsync(WindowsFormsApp1.ServiceReference1.UpdateTipRequest request) {
            return base.Channel.UpdateTipAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.UpdateTipResponse> UpdateTipAsync(int id_tip, string denumire, string caracteristici) {
            WindowsFormsApp1.ServiceReference1.UpdateTipRequest inValue = new WindowsFormsApp1.ServiceReference1.UpdateTipRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.UpdateTipRequestBody();
            inValue.Body.id_tip = id_tip;
            inValue.Body.denumire = denumire;
            inValue.Body.caracteristici = caracteristici;
            return ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).UpdateTipAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.InsertTipResponse WindowsFormsApp1.ServiceReference1.WebService1Soap.InsertTip(WindowsFormsApp1.ServiceReference1.InsertTipRequest request) {
            return base.Channel.InsertTip(request);
        }
        
        public void InsertTip(string denumire, string caracteristici) {
            WindowsFormsApp1.ServiceReference1.InsertTipRequest inValue = new WindowsFormsApp1.ServiceReference1.InsertTipRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.InsertTipRequestBody();
            inValue.Body.denumire = denumire;
            inValue.Body.caracteristici = caracteristici;
            WindowsFormsApp1.ServiceReference1.InsertTipResponse retVal = ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).InsertTip(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.InsertTipResponse> WindowsFormsApp1.ServiceReference1.WebService1Soap.InsertTipAsync(WindowsFormsApp1.ServiceReference1.InsertTipRequest request) {
            return base.Channel.InsertTipAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.InsertTipResponse> InsertTipAsync(string denumire, string caracteristici) {
            WindowsFormsApp1.ServiceReference1.InsertTipRequest inValue = new WindowsFormsApp1.ServiceReference1.InsertTipRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.InsertTipRequestBody();
            inValue.Body.denumire = denumire;
            inValue.Body.caracteristici = caracteristici;
            return ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).InsertTipAsync(inValue);
        }
        
        public void DeleteTip(int id_tip) {
            base.Channel.DeleteTip(id_tip);
        }
        
        public System.Threading.Tasks.Task DeleteTipAsync(int id_tip) {
            return base.Channel.DeleteTipAsync(id_tip);
        }
    }
}
